// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoq6S5y1HLjhfjptS_RYVh2LQkmeTowSY',
    appId: '1:279827145224:web:b63813a06a789422e5e7bd',
    messagingSenderId: '279827145224',
    projectId: 'hivechat-37a71',
    authDomain: 'hivechat-37a71.firebaseapp.com',
    storageBucket: 'hivechat-37a71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdD00y2k46Y4dr2NvQbg458xDy3e6tYk',
    appId: '1:279827145224:android:28aba6bb2fee18d5e5e7bd',
    messagingSenderId: '279827145224',
    projectId: 'hivechat-37a71',
    storageBucket: 'hivechat-37a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXXbg6LbC_mEz_Q5Pog8YybhU6IPXbJU',
    appId: '1:279827145224:ios:eaaa29e36b3a199de5e7bd',
    messagingSenderId: '279827145224',
    projectId: 'hivechat-37a71',
    storageBucket: 'hivechat-37a71.firebasestorage.app',
    iosBundleId: 'com.example.hivechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXXbg6LbC_mEz_Q5Pog8YybhU6IPXbJU',
    appId: '1:279827145224:ios:eaaa29e36b3a199de5e7bd',
    messagingSenderId: '279827145224',
    projectId: 'hivechat-37a71',
    storageBucket: 'hivechat-37a71.firebasestorage.app',
    iosBundleId: 'com.example.hivechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoq6S5y1HLjhfjptS_RYVh2LQkmeTowSY',
    appId: '1:279827145224:web:30aa9b2fbbe1356de5e7bd',
    messagingSenderId: '279827145224',
    projectId: 'hivechat-37a71',
    authDomain: 'hivechat-37a71.firebaseapp.com',
    storageBucket: 'hivechat-37a71.firebasestorage.app',
  );
}
